import crypto from 'node:crypto';
import { Wallet, SigningKey } from 'ethers';
import { createECDH } from 'node:crypto';

/**
 * Byte-for-byte port of the BlindMarket brief crypto, as generated by the
 * "Use from your agent" script (frontend/src/components/UseFromAgentModal.tsx
 * buildScript) and implemented identically in frontend/src/lib/crypto.ts and
 * backend/src/services/crypto.ts. Do not change wire formats:
 *   AES-256-GCM: [12-byte IV][16-byte auth tag][ciphertext]
 *   ECIES(secp256k1): [65-byte uncompressed ephemeral pubkey][AES-GCM blob]
 *     AES key = HKDF-SHA256(ECDH shared X, salt=empty, info='BlindMarket-ECIES-v1')
 */

export function generateAesKey(): Buffer {
  return crypto.randomBytes(32);
}

export function aesEncrypt(plain: Buffer, key: Buffer): Buffer {
  const iv = crypto.randomBytes(12);
  const c = crypto.createCipheriv('aes-256-gcm', key, iv);
  const ct = Buffer.concat([c.update(plain), c.final()]);
  return Buffer.concat([iv, c.getAuthTag(), ct]);
}

export function eciesEncrypt(payload: Buffer, recipientPubHex: string): Buffer {
  const pub = recipientPubHex.startsWith('0x') ? recipientPubHex.slice(2) : recipientPubHex;
  const eph = Wallet.createRandom();
  const shared = new SigningKey(eph.privateKey).computeSharedSecret('0x' + pub);
  const sharedX = Buffer.from(shared.slice(4, 68), 'hex'); // drop 0x04 prefix, keep X
  const aesKey = Buffer.from(crypto.hkdfSync('sha256', sharedX, Buffer.alloc(0), 'BlindMarket-ECIES-v1', 32));
  const ephPub = Buffer.from(SigningKey.computePublicKey(eph.privateKey, false).slice(2), 'hex');
  return Buffer.concat([ephPub, aesEncrypt(payload, aesKey)]);
}

export function sha256Hex(data: Buffer): string {
  return crypto.createHash('sha256').update(data).digest('hex');
}

const IV_LENGTH = 12, TAG_LENGTH = 16, KEY_LENGTH = 32, ECIES_PUBKEY_LENGTH = 65;

/** Inverse of aesEncrypt: [12 IV][16 tag][ciphertext] → plaintext. Mirrors
 *  backend/src/services/crypto.ts aesDecrypt exactly. */
export function aesDecrypt(blob: Buffer, key: Buffer): Buffer {
  if (key.length !== KEY_LENGTH) throw new Error(`AES key must be ${KEY_LENGTH} bytes, got ${key.length}`);
  if (blob.length < IV_LENGTH + TAG_LENGTH + 1) throw new Error(`AES blob too short: ${blob.length} bytes`);
  const iv = blob.subarray(0, IV_LENGTH);
  const tag = blob.subarray(IV_LENGTH, IV_LENGTH + TAG_LENGTH);
  const ct = blob.subarray(IV_LENGTH + TAG_LENGTH);
  const d = crypto.createDecipheriv('aes-256-gcm', key, iv, { authTagLength: TAG_LENGTH });
  d.setAuthTag(tag);
  return Buffer.concat([d.update(ct), d.final()]);
}

/**
 * Inverse of eciesEncrypt, for the secp256k1 wire format posters use to wrap
 * the brief's AES key to an executor: [65-byte ephemeral pubkey][AES-GCM blob].
 * Shared secret is the ECDH X coordinate — createECDH.computeSecret returns
 * exactly that, matching the `slice(4, 68)` the encrypt side takes — then
 * HKDF-SHA256 with the same info string. This is what lets an MCP executor
 * open a PRIVATE brief; before it existed, fetch_brief could only ever return
 * public briefs and told the caller to use a platform agent for the rest.
 */
export function eciesDecrypt(blob: Buffer, recipientPrivHex: string): Buffer {
  if (blob.length < ECIES_PUBKEY_LENGTH + IV_LENGTH + TAG_LENGTH + 1) throw new Error(`ECIES blob too short: ${blob.length} bytes`);
  const ephemeralPub = blob.subarray(0, ECIES_PUBKEY_LENGTH);
  const encrypted = blob.subarray(ECIES_PUBKEY_LENGTH);
  const ecdh = createECDH('secp256k1');
  ecdh.setPrivateKey(Buffer.from(recipientPrivHex.startsWith('0x') ? recipientPrivHex.slice(2) : recipientPrivHex, 'hex'));
  const sharedX = ecdh.computeSecret(ephemeralPub);
  const aesKey = Buffer.from(crypto.hkdfSync('sha256', sharedX, Buffer.alloc(0), 'BlindMarket-ECIES-v1', KEY_LENGTH));
  return aesDecrypt(encrypted, aesKey);
}

/** Uncompressed secp256k1 public key (hex, no 0x) for a private key — the
 *  exact form /a2a/register requires so posters can wrap keys to this executor. */
export function derivePublicKeyHex(privHex: string): string {
  return SigningKey.computePublicKey(privHex.startsWith('0x') ? privHex : `0x${privHex}`, false).slice(2);
}
